### ISSUE TITLE
"hhp browse" does not work?

### ISSUE THREAD

**Issue by Shougo** [kazu-yamamoto/hhp#11]
Hi.
I am `neco-ghc` maintainer.
https://github.com/eagletmt/neco-ghc

I have tested `hhp` instead of `ghc-mod`.
`hhp` 0.0.3 is installed by stack.

`hhpc browse` seems not work for me.
`hhpc browse -o System.IO` output is empty.

Am I missing something?
Can you show me the correct usage?

**Comment by kazu-yamamoto** [comment]
Here is an example:

```
% hhpc browse -o System.IO | head
AbsoluteSeek
AppendMode
BlockBuffering
BufferMode
CRLF
FilePath
Handle
HandlePosn
IO
IOMode
```

**Comment by Luc-Saccoccio** [comment]
I'm sorry, but I have the same problem on my side : 
```
% hhpc browse -o System.IO
%
```
It shows nothing. The version is `0.0.3`, installed using Stack.

**Comment by Shougo** [comment]
The documentation installation is needed?
I don't know how.

**Comment by kazu-yamamoto** [comment]
Ah. `hhp` does not support `stack`. `Cabal` only.

**Comment by Shougo** [comment]
Oh, I have not known that.

I have failed cabal installation...
So I have used stack.
