### ISSUE TITLE
[Feature Request] Add Stack support

### ISSUE THREAD

**Issue by Luc-Saccoccio** [kazu-yamamoto/hhp#12]
You said [this](https://github.com/kazu-yamamoto/hhp/issues/11#issuecomment-784537660) on another thread.

Is it possible to add support for Stack ?

**Comment by kazu-yamamoto** [comment]
HLS is very cool now. Is it worth to add a new feature to HHP?

**Comment by Luc-Saccoccio** [comment]
HLS seems a little big to me, so if it's not too much work, I think adding stack support can provide a lighter alternative to a Language Server.

**Comment by Luc-Saccoccio** [comment]
Nevermind, this project seems dead and I must admit HLS _is_ very cool. Closing the issue
